SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
CASE 
  WHEN STATUS = "DONE" THEN "거래완료"
  WHEN STATUS = "SALE" THEN "판매중"
  WHEN STATUS = "RESERVED" THEN "예약중"
  ELSE STATUS END AS STATUS
FROM USED_GOODS_BOARD
WHERE DATE_FORMAT(CREATED_DATE, "%y%m%d") = "221005"
ORDER BY BOARD_ID DESC
