SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, date_format(BOOK.PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY IN ("경제")
ORDER BY PUBLISHED_DATE